//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5448
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace IntecoAG.IBS.SyncService.Messages {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class XWVOXLOA {
        
        private int rETURNCODEField;
        
        private string vOTYPEField;
        
        private decimal vOCODEField;
        
        private string vOCOUNTRYCODEField;
        
        private string vOINNField;
        
        private string vOKPPField;
        
        private string vONAMEField;
        
        private string vOADDRField;
        
        private string vONAMEFULLField;
        
        private string vOUPUSERField;
        
        private string vOUPPGMField;
        
        private string vOUPTIMEField;
        
        private VOLIST[] vOLISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN-CODE")]
        public int RETURNCODE {
            get {
                return this.rETURNCODEField;
            }
            set {
                this.rETURNCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-TYPE")]
        public string VOTYPE {
            get {
                return this.vOTYPEField;
            }
            set {
                this.vOTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-CODE")]
        public decimal VOCODE {
            get {
                return this.vOCODEField;
            }
            set {
                this.vOCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-COUNTRY-CODE")]
        public string VOCOUNTRYCODE {
            get {
                return this.vOCOUNTRYCODEField;
            }
            set {
                this.vOCOUNTRYCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-INN")]
        public string VOINN {
            get {
                return this.vOINNField;
            }
            set {
                this.vOINNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-KPP")]
        public string VOKPP {
            get {
                return this.vOKPPField;
            }
            set {
                this.vOKPPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-NAME")]
        public string VONAME {
            get {
                return this.vONAMEField;
            }
            set {
                this.vONAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-ADDR")]
        public string VOADDR {
            get {
                return this.vOADDRField;
            }
            set {
                this.vOADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-NAME-FULL")]
        public string VONAMEFULL {
            get {
                return this.vONAMEFULLField;
            }
            set {
                this.vONAMEFULLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-UP-USER")]
        public string VOUPUSER {
            get {
                return this.vOUPUSERField;
            }
            set {
                this.vOUPUSERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-UP-PGM")]
        public string VOUPPGM {
            get {
                return this.vOUPPGMField;
            }
            set {
                this.vOUPPGMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-UP-TIME")]
        public string VOUPTIME {
            get {
                return this.vOUPTIMEField;
            }
            set {
                this.vOUPTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-LIST")]
        public VOLIST[] VOLIST {
            get {
                return this.vOLISTField;
            }
            set {
                this.vOLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("VO-LIST", Namespace="", IsNullable=false)]
    public partial class VOLIST {
        
        private string vOTYPEField;
        
        private decimal vOCODEField;
        
        private string vOCOUNTRYCODEField;
        
        private string vOINNField;
        
        private string vOKPPField;
        
        private string vONAMEField;
        
        private string vOADDRField;
        
        private string vONAMEFULLField;
        
        private string vOUPUSERField;
        
        private string vOUPPGMField;
        
        private string vOUPTIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-TYPE")]
        public string VOTYPE {
            get {
                return this.vOTYPEField;
            }
            set {
                this.vOTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-CODE")]
        public decimal VOCODE {
            get {
                return this.vOCODEField;
            }
            set {
                this.vOCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-COUNTRY-CODE")]
        public string VOCOUNTRYCODE {
            get {
                return this.vOCOUNTRYCODEField;
            }
            set {
                this.vOCOUNTRYCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-INN")]
        public string VOINN {
            get {
                return this.vOINNField;
            }
            set {
                this.vOINNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-KPP")]
        public string VOKPP {
            get {
                return this.vOKPPField;
            }
            set {
                this.vOKPPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-NAME")]
        public string VONAME {
            get {
                return this.vONAMEField;
            }
            set {
                this.vONAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-ADDR")]
        public string VOADDR {
            get {
                return this.vOADDRField;
            }
            set {
                this.vOADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-NAME-FULL")]
        public string VONAMEFULL {
            get {
                return this.vONAMEFULLField;
            }
            set {
                this.vONAMEFULLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-UP-USER")]
        public string VOUPUSER {
            get {
                return this.vOUPUSERField;
            }
            set {
                this.vOUPUSERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-UP-PGM")]
        public string VOUPPGM {
            get {
                return this.vOUPPGMField;
            }
            set {
                this.vOUPPGMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VO-UP-TIME")]
        public string VOUPTIME {
            get {
                return this.vOUPTIMEField;
            }
            set {
                this.vOUPTIMEField = value;
            }
        }
    }
}
