// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>IntecoAG.IBS.SyncService.Messages.XTB</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace IntecoAG.IBS.SyncService.Messages.XTB
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class XWTBXLOA : ServiceMessage<XWTBXLOA>
    {

        private int rETURNCODEField;

        private List<XWTBXLOATBLIST> tBLISTField;

        public XWTBXLOA()
        {
            this.tBLISTField = new List<XWTBXLOATBLIST>();
        }

        [System.Xml.Serialization.XmlElementAttribute("RETURN-CODE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int RETURNCODE
        {
            get
            {
                return this.rETURNCODEField;
            }
            set
            {
                this.rETURNCODEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-LIST", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public List<XWTBXLOATBLIST> TBLIST
        {
            get
            {
                return this.tBLISTField;
            }
            set
            {
                this.tBLISTField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class XWTBXLOATBLIST : ServiceMessage<XWTBXLOATBLIST>
    {

        private string tBCODEField;

        private decimal tBBUHCODEField;

        private string tBLASTNAMEField;

        private string tBFIRSTNAMEField;

        private string tBMIDDLENAMEField;

        private string tBSEXField;

        private decimal tBDPCODEField;

        private decimal tBDLCODEField;

        private string tBDLNAMEField;

        private string tBDTBEGINField;

        private string tBDTENDField;

        private bool tBISCLOSEDField;

        [System.Xml.Serialization.XmlElementAttribute("TB-CODE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string TBCODE
        {
            get
            {
                return this.tBCODEField;
            }
            set
            {
                this.tBCODEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-BUH-CODE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal TBBUHCODE
        {
            get
            {
                return this.tBBUHCODEField;
            }
            set
            {
                this.tBBUHCODEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-LAST-NAME", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string TBLASTNAME
        {
            get
            {
                return this.tBLASTNAMEField;
            }
            set
            {
                this.tBLASTNAMEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-FIRST-NAME", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string TBFIRSTNAME
        {
            get
            {
                return this.tBFIRSTNAMEField;
            }
            set
            {
                this.tBFIRSTNAMEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-MIDDLE-NAME", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string TBMIDDLENAME
        {
            get
            {
                return this.tBMIDDLENAMEField;
            }
            set
            {
                this.tBMIDDLENAMEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-SEX", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string TBSEX
        {
            get
            {
                return this.tBSEXField;
            }
            set
            {
                this.tBSEXField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-DP-CODE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public decimal TBDPCODE
        {
            get
            {
                return this.tBDPCODEField;
            }
            set
            {
                this.tBDPCODEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-DL-CODE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public decimal TBDLCODE
        {
            get
            {
                return this.tBDLCODEField;
            }
            set
            {
                this.tBDLCODEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-DL-NAME", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string TBDLNAME
        {
            get
            {
                return this.tBDLNAMEField;
            }
            set
            {
                this.tBDLNAMEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-DT-BEGIN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string TBDTBEGIN
        {
            get
            {
                return this.tBDTBEGINField;
            }
            set
            {
                this.tBDTBEGINField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-DT-END", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string TBDTEND
        {
            get
            {
                return this.tBDTENDField;
            }
            set
            {
                this.tBDTENDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("TB-IS-CLOSED", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public bool TBISCLOSED
        {
            get
            {
                return this.tBISCLOSEDField;
            }
            set
            {
                this.tBISCLOSEDField = value;
            }
        }
    }
}
