// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>IntecoAG.IBS.SyncService.Messages.XTB</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace IntecoAG.IBS.SyncService.Messages.XTB {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class XWTBALOA : ServiceMessage<XWTBALOA> {
        
        private int rETURNCODEField;
        
        private string tBANALTYPECODEField;
        
        private List<XWTBALOATBANALLIST> tBANALLISTField;
        
        public XWTBALOA() {
            this.tBANALLISTField = new List<XWTBALOATBANALLIST>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RETURN-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int RETURNCODE {
            get {
                return this.rETURNCODEField;
            }
            set {
                this.rETURNCODEField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TB-ANAL-TYPE-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TBANALTYPECODE {
            get {
                return this.tBANALTYPECODEField;
            }
            set {
                this.tBANALTYPECODEField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TB-ANAL-LIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public List<XWTBALOATBANALLIST> TBANALLIST {
            get {
                return this.tBANALLISTField;
            }
            set {
                this.tBANALLISTField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XWTBALOATBANALLIST : ServiceMessage<XWTBALOATBANALLIST> {
        
        private string tBCODEField;
        
        private decimal tBBUHCODEField;
        
        private string tBNAMEField;
        
        [System.Xml.Serialization.XmlElementAttribute("TB-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TBCODE {
            get {
                return this.tBCODEField;
            }
            set {
                this.tBCODEField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TB-BUH-CODE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal TBBUHCODE {
            get {
                return this.tBBUHCODEField;
            }
            set {
                this.tBBUHCODEField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TB-NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TBNAME {
            get {
                return this.tBNAMEField;
            }
            set {
                this.tBNAMEField = value;
            }
        }
    }
}
