// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>IntecoAG.IBS.SyncService.Messages.XDP</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace IntecoAG.IBS.SyncService.Messages.XDP {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class XWDPXLOA : ServiceMessage<XWDPXLOA> {

        private int rETURNCODEField;

        private List<XWDPXLOADPLIST> dPLISTField;

        public XWDPXLOA() {
            this.dPLISTField = new List<XWDPXLOADPLIST>();
        }

        [System.Xml.Serialization.XmlElementAttribute("RETURN-CODE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int RETURNCODE {
            get {
                return this.rETURNCODEField;
            }
            set {
                this.rETURNCODEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DP-LIST", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public List<XWDPXLOADPLIST> DPLIST {
            get {
                return this.dPLISTField;
            }
            set {
                this.dPLISTField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class XWDPXLOADPLIST : ServiceMessage<XWDPXLOADPLIST> {

        private string dPCODEField;

        private decimal dPBUHCODEField;

        private string dPNAMEField;

        private string dPNAMEFULLField;

        private string dPDTBEGINField;

        private string dPDTENDField;

        private bool dPISCLOSEDField;

        [System.Xml.Serialization.XmlElementAttribute("DP-CODE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string DPCODE {
            get {
                return this.dPCODEField;
            }
            set {
                this.dPCODEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DP-BUH-CODE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal DPBUHCODE {
            get {
                return this.dPBUHCODEField;
            }
            set {
                this.dPBUHCODEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DP-NAME", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DPNAME {
            get {
                return this.dPNAMEField;
            }
            set {
                this.dPNAMEField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DP-NAME-FULL", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string DPNAMEFULL {
            get {
                return this.dPNAMEFULLField;
            }
            set {
                this.dPNAMEFULLField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DP-DT-BEGIN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string DPDTBEGIN {
            get {
                return this.dPDTBEGINField;
            }
            set {
                this.dPDTBEGINField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DP-DT-END", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string DPDTEND {
            get {
                return this.dPDTENDField;
            }
            set {
                this.dPDTENDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DP-IS-CLOSED", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public bool DPISCLOSED {
            get {
                return this.dPISCLOSEDField;
            }
            set {
                this.dPISCLOSEDField = value;
            }
        }
    }
}
